language: android
dist: trusty
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - add-on
    - extra
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter doctor --android-licenses
  - chmod +x generate-apks.sh
script:
  - ./flutter/bin/flutter build apk
after_success:
  - ./generate-apks.sh
cache:
  directories:
    - $HOME/.pub-cache
